import type { Metadata } from "next";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { DialogService } from "@/components/dialog-service/dialog-service";
import { pretendard } from "@/config/font";
import { ReactQueryProvider } from "@/lib/react-query/provider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="scroll-smooth" data-scroll-behavior="smooth">
      <body
        className={cn(pretendard.className, pretendard.variable, "antialiased")}
      >
        <ReactQueryProvider>
          <NuqsAdapter>{children}</NuqsAdapter>
        </ReactQueryProvider>

        <DialogService />
      </body>
    </html>
  );
}
